# Generated by Django 3.0.2 on 2020-02-29 06:05

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerSummaryAverage',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='dinner_summary_average')),
                ('keyword', models.CharField(max_length=30, null=True, verbose_name='keyword')),
                ('keyword_sentiment_ave_score', models.FloatField(null=True, verbose_name='sentiment_ave_score')),
            ],
            options={
                'verbose_name': 'dinner_summary_average',
                'verbose_name_plural': 'dinner_summary_average',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='StoreID')),
                ('store_name', models.CharField(max_length=30, verbose_name='StoreName')),
                ('tabelog_score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Tabelog_score')),
                ('station', models.CharField(max_length=20, null=True, verbose_name='最寄り駅')),
                ('lunch_price', models.CharField(max_length=10, null=True, verbose_name='ランチ価格')),
                ('dinner_price', models.CharField(max_length=10, null=True, verbose_name='ディナー価格')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='住所')),
                ('phone_num', models.CharField(default='000', max_length=11, verbose_name='電話番号')),
                ('opening_time', models.CharField(max_length=20, null=True, verbose_name='営業時間')),
                ('regular_holiday', models.CharField(max_length=10, null=True, verbose_name='定休日')),
                ('url', models.URLField(null=True, verbose_name='url')),
                ('latitude', models.FloatField(null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='longtitude')),
                ('retty_score', models.PositiveIntegerField(null=True, verbose_name='Retty_score')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時')),
                ('tabelog_growth_rate', models.FloatField(null=True, verbose_name='食べログ伸び率')),
                ('retty_growth_rate', models.FloatField(null=True, verbose_name='Retty伸び率')),
            ],
            options={
                'verbose_name': 'store data',
                'verbose_name_plural': 'store data',
            },
        ),
        migrations.CreateModel(
            name='TabelogHistory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='tabelog_history_ID')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='user score')),
                ('nth', models.PositiveIntegerField(verbose_name='何回目')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'tabelog_history',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='review_dinnerID')),
                ('ld_id', models.IntegerField(default=0, verbose_name='昼OR夜')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='user score')),
                ('review', models.TextField(null=True, verbose_name='review content')),
                ('is_new', models.BooleanField(default=True, null=True, verbose_name='新しく取得されたレビューかどうか？')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'review',
            },
        ),
        migrations.CreateModel(
            name='RettyHistory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='retty_history_ID')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='user score')),
                ('nth', models.PositiveIntegerField(verbose_name='何回目')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'retty_history',
            },
        ),
        migrations.CreateModel(
            name='LunchStoreSummary',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lunch_store_summary')),
                ('keyword1', models.CharField(max_length=20, null=True, verbose_name='keyword1')),
                ('keyword1_modifier1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'lunch_store_summary',
                'verbose_name_plural': 'lunch_store_summary',
            },
        ),
        migrations.CreateModel(
            name='LunchSentimentResult',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lunch_sentimentanalytics_result')),
                ('sentense', models.CharField(max_length=1000, null=True, verbose_name='sentense')),
                ('sentiment', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='sentiment')),
                ('magnitude', models.FloatField(null=True, verbose_name='magunitude')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Review', verbose_name='lunch_review')),
            ],
            options={
                'verbose_name': 'lunch sentiment analytics results',
                'verbose_name_plural': 'lunch sentiment analytics results',
            },
        ),
        migrations.CreateModel(
            name='LunchImportantWords',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='inportantwordID')),
                ('all_words_num', models.IntegerField(null=True, verbose_name='総単語数')),
                ('key_words', models.CharField(max_length=20, null=True, verbose_name='軸単語')),
                ('key_words_nums', models.IntegerField(null=True, verbose_name='軸単語出現数')),
                ('key_words_count', models.IntegerField(null=True, verbose_name='軸単語登場回数')),
                ('keyword_modifier1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'lunch important words',
                'verbose_name_plural': 'lunch important words',
            },
        ),
        migrations.CreateModel(
            name='DinnerStoreSummary',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='dinner_store_summary')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時')),
                ('keyword', models.CharField(max_length=20, null=True, verbose_name='keyword1')),
                ('keyword_sentiment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, verbose_name='keyword_sentiment'), null=True, size=None)),
                ('keyword_modifier1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier6', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'dinner_store_summary',
                'verbose_name_plural': 'dinner_store_summary',
            },
        ),
        migrations.CreateModel(
            name='DinnerSentimentResult',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lunch_sentimentanalytics_result')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時')),
                ('sentense', models.CharField(max_length=1000, null=True, verbose_name='sentense')),
                ('sentiment', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='sentiment')),
                ('magnitude', models.FloatField(null=True, verbose_name='magunitude')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Review', verbose_name='dinner_review')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'dinner sentiment analytics results',
                'verbose_name_plural': 'dinner sentiment analytics results',
            },
        ),
        migrations.CreateModel(
            name='DinnerImportantWords',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='inportantwordID')),
                ('all_words_num', models.IntegerField(null=True, verbose_name='総単語数')),
                ('key_words', models.CharField(max_length=20, null=True, verbose_name='軸単語')),
                ('key_words_nums', models.IntegerField(null=True, verbose_name='軸単語出現数')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('keyword_modifier1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('keyword_modifier5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'dinner important words',
                'verbose_name_plural': 'dinner important words',
            },
        ),
    ]
