# Generated by Django 3.0.2 on 2020-01-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchReview',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='review_lunchID')),
                ('score', models.FloatField(null=True, verbose_name='each score')),
                ('content', models.TextField(null=True, verbose_name='review content')),
            ],
            options={
                'verbose_name': 'review_lunch',
                'verbose_name_plural': 'review_lunch',
            },
        ),
        migrations.CreateModel(
            name='LunchStoreSummary',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='lunch_store_summary')),
                ('keyword1', models.CharField(max_length=20, null=True, verbose_name='keyword1')),
                ('keyword2', models.CharField(max_length=20, null=True, verbose_name='keyword2')),
                ('keyword3', models.CharField(max_length=20, null=True, verbose_name='keyword3')),
                ('keyword4', models.CharField(max_length=20, null=True, verbose_name='keyword4')),
                ('keyword5', models.CharField(max_length=20, null=True, verbose_name='keyword5')),
                ('keyword6', models.CharField(max_length=20, null=True, verbose_name='keyword6')),
                ('keyword7', models.CharField(max_length=20, null=True, verbose_name='keyword7')),
                ('keyword8', models.CharField(max_length=20, null=True, verbose_name='keyword8')),
                ('keyword9', models.CharField(max_length=20, null=True, verbose_name='keyword9')),
                ('keyword10', models.CharField(max_length=20, null=True, verbose_name='keyword10')),
            ],
            options={
                'verbose_name': 'lunch_store_summary',
                'verbose_name_plural': 'lunch_store_summary',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='StoreID')),
                ('store_name', models.CharField(max_length=30, verbose_name='StoreName')),
                ('tabelog_score', models.FloatField(null=True, verbose_name='Tabelog_score')),
                ('retty_score', models.PositiveIntegerField(null=True, verbose_name='Retty_score')),
            ],
            options={
                'verbose_name': 'store data',
                'verbose_name_plural': 'store data',
            },
        ),
        migrations.CreateModel(
            name='LunchSentimentResult',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lunch_sentimentanalytics_result')),
                ('sentense', models.CharField(max_length=100, null=True, verbose_name='sentense')),
                ('sentiment', models.FloatField(null=True, verbose_name='sentiment')),
                ('magnitude', models.FloatField(null=True, verbose_name='magunitude')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.LunchReview', verbose_name='lunch_review')),
            ],
            options={
                'verbose_name': 'sentiment analytics results',
                'verbose_name_plural': 'sentiment analytics results',
            },
        ),
        migrations.AddField(
            model_name='lunchreview',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store'),
        ),
        migrations.CreateModel(
            name='LunchImportantWords',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='inportantwordID')),
                ('key_words1', models.CharField(max_length=20, null=True, verbose_name='軸単語1')),
                ('key_words1_count', models.IntegerField(null=True, verbose_name='軸単語1登場回数')),
                ('modifier_word1', models.CharField(max_length=20, null=True, verbose_name='修飾語1')),
                ('modifier_word2', models.CharField(max_length=20, null=True, verbose_name='修飾語2')),
                ('modifier_word3', models.CharField(max_length=20, null=True, verbose_name='修飾語3')),
                ('modifier_word4', models.CharField(max_length=20, null=True, verbose_name='修飾語4')),
                ('modifier_word5', models.CharField(max_length=20, null=True, verbose_name='修飾語5')),
                ('modifier_word6', models.CharField(max_length=20, null=True, verbose_name='修飾語6')),
                ('modifier_word7', models.CharField(max_length=20, null=True, verbose_name='修飾語7')),
                ('modifier_word8', models.CharField(max_length=20, null=True, verbose_name='修飾語8')),
                ('modifier_word9', models.CharField(max_length=20, null=True, verbose_name='修飾語9')),
                ('modifier_word10', models.CharField(max_length=20, null=True, verbose_name='修飾語10')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'important words',
                'verbose_name_plural': 'important words',
            },
        ),
        migrations.CreateModel(
            name='DinnerReview',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='review_dinnerID')),
                ('score', models.FloatField(null=True, verbose_name='user score')),
                ('content', models.TextField(null=True, verbose_name='review content')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'review_dinner',
            },
        ),
    ]
