# Generated by Django 3.0.2 on 2020-01-13 07:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchstoresummary',
            name='keyword1_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
    ]
