# Generated by Django 3.0.2 on 2020-01-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchreview',
            options={'verbose_name': 'review_lunch', 'verbose_name_plural': 'review_lunch'},
        ),
        migrations.AddField(
            model_name='store',
            name='retty_score',
            field=models.PositiveIntegerField(null=True, verbose_name='Retty_score'),
        ),
        migrations.AddField(
            model_name='store',
            name='tabelog_score',
            field=models.FloatField(null=True, verbose_name='Tabelog_score'),
        ),
        migrations.AlterField(
            model_name='lunchreview',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='review_lunchID'),
        ),
        migrations.CreateModel(
            name='DinnerReview',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='review_dinnerID')),
                ('score', models.FloatField(null=True, verbose_name='user score')),
                ('content', models.TextField(null=True, verbose_name='review content')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'review_dinner',
            },
        ),
    ]
