# Generated by Django 3.0.2 on 2020-02-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_sex',
            field=models.IntegerField(choices=[(0, '不明'), (1, '男性'), (2, '女性')], null=True, verbose_name='性別'),
        ),
    ]
