# Generated by Django 3.0.2 on 2020-02-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='StoreID'),
        ),
    ]
