# Generated by Django 3.0.2 on 2020-01-18 06:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0004_auto_20200118_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='key_words1',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='key_words1_count',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word1',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word10',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word2',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word3',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word4',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word5',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word6',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word7',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word8',
        ),
        migrations.RemoveField(
            model_name='lunchimportantwords',
            name='modifier_word9',
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='all_words_num',
            field=models.IntegerField(null=True, verbose_name='総単語数'),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='key_words',
            field=models.CharField(max_length=20, null=True, verbose_name='軸単語'),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='key_words_count',
            field=models.IntegerField(null=True, verbose_name='軸単語登場回数'),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='key_words_nums',
            field=models.IntegerField(null=True, verbose_name='軸単語出現数'),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='keyword_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='keyword_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='keyword_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='keyword_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='lunchimportantwords',
            name='keyword_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
    ]
