# Generated by Django 3.0.2 on 2020-02-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0006_auto_20200202_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerimportantwords',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store'),
        ),
    ]
