# Generated by Django 3.0.2 on 2020-02-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0008_auto_20200202_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnersentimentresult',
            options={'verbose_name': 'dinner sentiment analytics results', 'verbose_name_plural': 'dinner sentiment analytics results'},
        ),
        migrations.AlterModelOptions(
            name='lunchsentimentresult',
            options={'verbose_name': 'lunch sentiment analytics results', 'verbose_name_plural': 'lunch sentiment analytics results'},
        ),
        migrations.AddField(
            model_name='dinnersentimentresult',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store'),
        ),
    ]
