# Generated by Django 3.0.2 on 2020-02-02 09:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0009_auto_20200202_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword10',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword7',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword8',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword9',
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword1_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword1_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword1_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword1_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword1_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword2_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword3_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword4_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword5_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword6_modifier6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='keyword_modifier1'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store'),
        ),
        migrations.AddField(
            model_name='lunchstoresummary',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store'),
        ),
    ]
