# Generated by Django 3.0.2 on 2020-02-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0011_auto_20200202_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword_modifier10',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword_modifier7',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword_modifier8',
        ),
        migrations.RemoveField(
            model_name='dinnerstoresummary',
            name='keyword_modifier9',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword10',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword2',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword3',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword4',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword5',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword6',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword7',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword8',
        ),
        migrations.RemoveField(
            model_name='lunchstoresummary',
            name='keyword9',
        ),
    ]
