# Generated by Django 3.0.2 on 2020-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0012_auto_20200202_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerstoresummary',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='dinner_store_summary'),
        ),
        migrations.AlterField(
            model_name='lunchstoresummary',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lunch_store_summary'),
        ),
    ]
