# Generated by Django 3.0.2 on 2020-02-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0013_auto_20200202_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnersentimentresult',
            name='sentense',
            field=models.CharField(max_length=300, null=True, verbose_name='sentense'),
        ),
        migrations.AlterField(
            model_name='lunchsentimentresult',
            name='sentense',
            field=models.CharField(max_length=300, null=True, verbose_name='sentense'),
        ),
    ]
