# Generated by Django 3.0.2 on 2020-02-09 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0015_auto_20200209_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='keyword_sentiment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, verbose_name='keyword_sentiment'), null=True, size=None),
        ),
    ]
