# Generated by Django 3.0.2 on 2020-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0016_dinnerstoresummary_keyword_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerimportantwords',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='dinnersentimentresult',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='dinnersentimentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='dinnerstoresummary',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='データ作成日時'),
        ),
    ]
