# Generated by Django 3.0.2 on 2020-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0017_auto_20200216_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerSummaryAverage',
            fields=[
                ('id',
                 models.CharField(
                     max_length=10,
                     primary_key=True,
                     serialize=False,
                     verbose_name='dinner_summary_average')),
                ('keyword',
                 models.CharField(
                     max_length=30,
                     null=True,
                     verbose_name='keyword')),
                ('keyword_sentiment_ave_score',
                 models.FloatField(
                     null=True,
                     verbose_name='sentiment_ave_score')),
            ],
            options={
                'verbose_name': 'dinner_summary_average',
                'verbose_name_plural': 'dinner_summary_average',
            },
        ),
        migrations.AddField(
            model_name='Review',
            name='is_new',
            field=models.BooleanField(
                null=True,
                verbose_name='新しく取得されたレビューかどうか？'),
        ),
    ]
