# Generated by Django 3.0.2 on 2020-02-16 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0018_auto_20200216_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelogHistory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='review_dinnerID')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='user score')),
                ('nth', models.PositiveIntegerField(verbose_name='何回目')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'tabelog_history',
            },
        ),
        migrations.CreateModel(
            name='RettyHistory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='review_dinnerID')),
                ('score', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='user score')),
                ('nth', models.PositiveIntegerField(verbose_name='何回目')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='データ作成日時')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushi_app.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'retty_history',
            },
        ),
    ]
