# Generated by Django 3.0.2 on 2020-02-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0019_rettyhistory_tabeloghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='retty_growth_rate',
            field=models.FloatField(null=True, verbose_name='Retty伸び率'),
        ),
        migrations.AddField(
            model_name='store',
            name='tabelog_growth_rate',
            field=models.FloatField(null=True, verbose_name='食べログ伸び率'),
        ),
        migrations.AlterField(
            model_name='rettyhistory',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='retty_history_ID'),
        ),
        migrations.AlterField(
            model_name='tabeloghistory',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='tabelog_history_ID'),
        ),
    ]
