# Generated by Django 3.0.2 on 2020-02-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0021_Review_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='store',
            name='dinner_price',
            field=models.CharField(max_length=10, null=True, verbose_name='ディナー価格'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='longtitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='lunch_price',
            field=models.CharField(max_length=10, null=True, verbose_name='ランチ価格'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.CharField(max_length=20, null=True, verbose_name='営業時間'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_num',
            field=models.CharField(default='000', max_length=11, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='store',
            name='regular_holiday',
            field=models.CharField(max_length=10, null=True, verbose_name='定休日'),
        ),
        migrations.AddField(
            model_name='store',
            name='station',
            field=models.CharField(max_length=20, null=True, verbose_name='最寄り駅'),
        ),
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.URLField(null=True, verbose_name='url'),
        ),
    ]
